---
- name: Backup dot files and configs to GitHub
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Read GitHub Token from .github_token file
      slurp:
        src: ~/.github_token
      register: github_token_file

    - name: Set GitHub Token
      set_fact:
        github_token: "{{ github_token_file.content | b64decode | regex_replace('\\s+$', '') }}"

    - name: Clone the GitHub repository
      git:
        repo: "https://{{ github_token }}@github.com/diegomrepo/my-config.git"
        dest: /tmp/backups
        clone: yes
        update: yes
        force: yes
      become: true

    - name: Backup dot files and configs
      find:
        hidden: true
        paths:
          - "{{ ansible_env.HOME }}"
        patterns:
          - '.*'
          - '*.conf'
          - '*.cfg'
          - '*.ini'
        file_type: file
      register: backup_files

    - name: Copy backup files to local directory
      copy:
        src: "{{ item.path }}"
        dest: /tmp/backups/{{ item.path | basename }}
      with_items: "{{ backup_files.files }}"
      become: true

    - name: Check for changes
      command: git status --porcelain
      args:
        chdir: /tmp/backups
      register: git_status

    - name: Commit and push backup files to GitHub if changes
      when: git_status.stdout_lines
      become: true
      git:
        repo: "https://{{ github_token }}@github.com/diegomrepo/my-config.git"
        dest: /tmp/backups
        update: yes
        force: yes
        remote: origin
        pull: yes
        push: yes
        commit_msg: "Backup {{ ansible_date_time.iso8601 }}"
      register: git_result
